/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":domain-implementations:jdbc"))
    implementation(project(":domain-implementations:JPA"))
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.0")
    implementation("com.mysql:mysql-connector-j:8.3.0")
    implementation(project(":domain-implementations:file"))
    implementation("com.github.freva:ascii-table:1.8.0")
    implementation("com.athaydes.rawhttp:rawhttp-core:2.6.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.0")

}

application {
    // Define the main class for the application.
    mainClass = "org.example.clients.console.App"
}