/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}
repositories {
    mavenCentral()
}


dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":domain-implementations:jdbc"))
    implementation(project(":domain-implementations:JPA"))
    implementation("com.mysql:mysql-connector-j:8.3.0")
    implementation(project(":domain-implementations:file"))
    implementation("com.github.freva:ascii-table:1.8.0")
    implementation ("com.athaydes.rawhttp:rawhttp-core:2.5.1")
    implementation ("org.hibernate:hibernate-core:5.6.3.Final")
    implementation ("javax.persistence:javax.persistence-api:2.2")
    implementation ("com.fasterxml.jackson.core:jackson-databind:2.13.1")
    implementation ("jakarta.persistence:jakarta.persistence-api:3.1.0")
    implementation ("org.slf4j:slf4j-api:1.7.30")
    implementation ("org.slf4j:slf4j-simple:1.7.30")
    implementation("com.athaydes.rawhttp:rawhttp-core:2.6.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")

}

application {
    mainClass = "org.example.app.App"
}
