GET http://localhost:8080/client
Accept: application/json
###
GET http://localhost:8080/client/1
Accept: application/json
###
DELETE http://localhost:9998/client/1
Accept: application/json
###
PUT http://localhost:9998/client/2
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "dni": "12345678A",
  "name": "Client A (Updated)",
  "phone": "111222333",
  "addresses": {
    "location": "Street A (Updated)"
  },
  "shoeStores": {
    "id": 1,
    "name": "Shoe Store A (Updated)",

  }
}

###
POST http://localhost:9998/client
Accept: application/json
Content-Type: application/json

{
  "dni": "12345678A",
  "name": "John Doe",
  "phone": "555-1234",
  "address": {
    "location": "Near the central park"
  }
}

###