GET http://localhost:9998/client/
Accept: application/json

####
POST http://localhost:9998/client
Accept: application/json
Content-Type: application/json

{
  "dni": "87654321B",
  "name": "Albert",
  "phone": "987654321",
  "addresses": {
    "location": "Passeig de Gràcia"
  },
  "shoeStores": {
    "name": "Elegant Shoes",
    "owner": "Anna",
    "location": "Barcelona"
  }
}



####

PUT http://localhost:9998/client/14
Accept: application/json
Content-Type: application/json

{
  "addresses": {
    "location": "123 Main St"
  },
  "dni": "12345678A",
  "name": "aaaaaaaa",
  "phone": "123456789",
  "shoeStores": {
    "name": "Doe's Shoes",
    "owner": "John Doe",
    "location": "Downtown"
  }
}

####

DELETE http://localhost:9998/client/
Accept: application/json

