###
GET http://localhost:9998/model
Accept: application/json
###
###
GET http://localhost:9998/model/2
Accept: application/json
###
###
DELETE http://localhost:9998/model/2
Accept: application/json
###
###

###
###

###