/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}


dependencies{
    implementation("org.bouncycastle:bcprov-jdk18on:1.78")
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from ("./src/main/resources") {
        include("META-INF/services/cat.fcardara.bandhub.domain.services.ModelCreator")
    }
}